const SITE_BASE='/Karenza';
const siteUrl=value=>value.startsWith('/')&&!value.startsWith('//')&&value!==SITE_BASE&&!value.startsWith(SITE_BASE+'/')?SITE_BASE+value:value;
const routePath=()=>{const path=location.pathname;return (path===SITE_BASE?'/' : path.startsWith(SITE_BASE+'/')?path.slice(SITE_BASE.length):path).replace(/\/+$/, '')||'/';};
const fold=s=>String(s).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
let products=[],sections=[],collections={},cart=[],pageLimit=24,collectionFilter='',sortBy='featured';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>'$'+Number(n).toLocaleString('es-ES',{maximumFractionDigits:2});
const getProduct=h=>products.find(p=>p.handle===h), section=k=>sections.find(s=>s.key===k);
const titles={'all':'Todos los productos','new-arrivals':'Novedades','hats':'Gorros','muttonhead':'Muttonhead','accessories':'Accesorios','t-shirts':'Camisetas','jackets':'Chaquetas','sweatshirt':'Sudaderas','apparel':'Ropa','naked-and-famous':'Naked and Famous','homegoods':'Hogar','sweatpants':'Pantalones deportivos','outerwear':'Abrigos','sale':'Ofertas','juniper-ridge':'Juniper Ridge','bather':'Bather','beside':'Beside'};
try{cart=JSON.parse(localStorage.getItem('masion-cart')||'[]');if(!Array.isArray(cart))cart=[];}catch{cart=[];}
const card=p=>p?`<article class="product-card"><div class="photo-wrap"><a class="product-photo" href="/Karenza/products/${p.handle}">${img(p.images[0],p.title)}${p.images[1]?`<img class="secondary" src="${p.images[1]}" alt="${esc(p.title)} detalle" loading="lazy">`:''}</a><button class="quick-view" data-quick="${p.handle}">Vista rápida</button></div><a class="product-title" href="/Karenza/products/${p.handle}">${esc(p.title)}</a><div class="vendor">${esc(p.vendor.toUpperCase())}</div><div class="price">${money(p.price)}</div></article>`:'';
const img=(url,alt='',cl='')=>url?`<img src="${url}" alt="${esc(alt)}" class="${cl}" loading="lazy">`:`<div class="image-unavailable" role="img" aria-label="${esc(alt)}: imagen no disponible">Imagen no disponible</div>`;
const link=(h,t)=>`<a href="/Karenza/collections/${h}">${t||titles[h]||h}</a>`;
function home(){return `<section class="hero"><img id="hero-image" src="/Karenza/assets/hero.jpg" alt="Suéter mostaza de cuello alto, tejido para tu comodidad" fetchpriority="high"><div class="hero-copy"><p class="eyebrow" id="hero-eyebrow">DONDE LA CALIDAD</p><h1 id="hero-heading">SE UNE A LA COMODIDAD</h1><p class="hero-subtitle" id="hero-subtitle">Prendas esenciales de calidad en seis nuevos colores</p><a class="button brown" id="hero-link" href="/Karenza/collections/hats">EXPLORAR AHORA</a></div><div class="slide-controls">${[0,1,2].map(i=>`<button data-slide="${i}" aria-label="Mostrar diapositiva ${i+1}" aria-current="${i===0}"></button>`).join('')}</div></section>
<section class="section"><h2>NOVEDADES — GORROS</h2><div class="product-grid">${['chunky-toque-fawn-2','chunky-toque-army-1','chunky-toque-black-1','chunky-toque-maroon'].map(h=>card(getProduct(h))).join('')}</div></section>
<section class="together hotspot-photo">${img(section('made_together').image,'Prendas de punto superpuestas y un cárdigan color crema')}<button class="hotspot" style="left:60%;top:53%" data-quick="blazer-heavy-velvet-twill-brown" aria-label="Ver el blazer">+</button><button class="hotspot" style="left:76%;top:70%" data-quick="alexis-journey-card-party-mountain-paper-co" aria-label="Ver la tarjeta">+</button><div class="editorial-copy"><p class="eyebrow">COMPRA EL LOOK</p><h2>HECHOS PARA COMBINAR</h2><p>Prendas que se complementan, sin importar cómo las combines. Diseñadas para vestir con naturalidad en cualquier ocasión.</p></div></section>
<section class="promo-pair section">${section('promos_two').tiles.map((t,i)=>`<a class="image-tile" href="/Karenza/collections/${i?'all':'accessories'}">${img(t.image,t.heading)}<div class="tile-copy"><h2>${t.heading.toUpperCase()}</h2>${i?'<p>Descubre tus esenciales para el invierno</p>':''}<span class="button translucent">${t.cta}</span></div></a>`).join('')}</section>
<section class="section categories"><h2>COMPRA POR CATEGORÍA</h2><div class="category-grid three">${section('shop_by_category').tiles.map(t=>`<a href="${siteUrl(new URL(t.href).pathname)}">${img(t.image,t.name)}<h3>${t.name.toUpperCase()}</h3></a>`).join('')}</div></section>
<section class="promo-three section">${section('promos_three').tiles.map((t,i)=>`<a class="image-tile" href="${siteUrl(['/collections/apparel','/collections/naked-and-famous','/pages/contact-us'][i])}">${img(t.image,t.heading)}<div class="tile-copy"><p class="eyebrow">${t.eyebrow.toUpperCase()}</p><h2>${t.heading.toUpperCase()}</h2><p>${['Prendas atemporales que definen tu estilo.','Denim cuidadosamente confeccionado para quienes aprecian la calidad.','337 Roncesvalles Ave, Toronto'][i]}</p><span class="button translucent">${t.cta}</span></div></a>`).join('')}</section>
<section class="brand-strip section" aria-label="Nuestras marcas">${section('brand_logos').images.map((src,i)=>`<a href="/Karenza/collections/${['muttonhead','naked-and-famous','juniper-ridge','bather','beside'][i]}">${img(src,['Muttonhead','Naked and Famous','Juniper Ridge','Bather','Beside'][i])}</a>`).join('')}</section>
<section class="section shoppable"><h2>COMPRA EL LOOK</h2><div class="look-layout"><div id="look-product">${card(getProduct('bear-pocket-tee-black'))}</div><div class="hotspot-photo">${img(section('shop_the_look').image,'Prendas esenciales combinadas para el día a día')}${section('shop_the_look').products.map((p,i)=>`<button class="hotspot" style="left:${[39,63,55][i]}%;top:${[35,50,76][i]}%" data-look="${new URL(p.href).pathname.split('/').pop()}" aria-label="Mostrar ${esc(p.name)}">+</button>`).join('')}</div></div></section>
<section class="wildwood image-tile">${img(section('wildwood').image,'Esenciales Wildwood con luz natural')}<div class="tile-copy"><p class="eyebrow">ARTESANÍA ATEMPORAL</p><h2>ESENCIALES WILDWOOD</h2><p>La elegancia nace de la autenticidad, la delicadeza y la naturalidad. Un estilo sofisticado con una presencia que se hace notar. Nuestra colección Wildwood combina artesanía atemporal y sensibilidad contemporánea.</p><a class="button" href="/Karenza/collections/homegoods">EXPLORAR COLECCIÓN</a></div></section>
<section class="section categories"><h2>EXPLORA LAS CATEGORÍAS</h2><div class="category-grid four">${section('shop_categories').tiles.map((t,i)=>`<a href="/Karenza/collections/${['hats','sweatpants','jackets','homegoods'][i]}">${img(t.image,t.name)}<h3>${t.name.toUpperCase()}</h3></a>`).join('')}</div></section>
<section class="section feature-product"><div class="editorial-copy"><p class="eyebrow">ESTÁ DE VUELTA</p><h2>LA GORRA DE 5 PANELES</h2><p>De vuelta para acompañarte cada día. Ahora disponible en nuestro característico verde bosque.</p><a class="button" href="/Karenza/products/naked-famous-crewneck-heavyweight-terry-black">VER COLORES</a></div><a class="feature-photo" href="/Karenza/products/naked-famous-crewneck-heavyweight-terry-black">${img(section('five_panel_hat').images[0],'Sudadera negra de tejido grueso Naked & Famous')}<span class="feature-price"><small>Nuevo</small>${money(159)}</span></a><a class="feature-detail" href="/Karenza/products/naked-famous-crewneck-heavyweight-terry-black">${img(section('five_panel_hat').images[1],'Detalle de la sudadera negra de tejido grueso')}</a></section>
<section class="section"><div class="section-heading"><h2>COMPRA SUDADERAS</h2><a class="button outline" href="/Karenza/collections/sweatshirt">VER TODO</a></div><div class="product-grid">${section('sweatshirts').products.map(p=>card(products.find(x=>x.title===p.name))).join('')}</div></section>
<section class="sale-banner"><div><h2>OFERTAS DE BLACK FRIDAY</h2><p>Solo este fin de semana: 30 % de descuento adicional en todas las colecciones de otoño e invierno.</p></div><div class="countdown" aria-label="La cuenta regresiva de la promoción ha terminado">${['DÍAS','HORAS','MINUTOS','SEGUNDOS'].map(t=>`<div><span>00</span><small>${t}</small></div>`).join('')}</div></section>
<section class="photo-strip" aria-label="La selección de Karenza">${section('photo_strip').images.map((src,i)=>`<a href="/Karenza/collections/${['apparel','hats','accessories','new-arrivals','sweatshirt','all'][i]}">${img(src,'La selección de Karenza — '+(i+1))}</a>`).join('')}</section>`;}
function footer(){return `<div class="footer-grid"><div><h3>TIENDA</h3>${['apparel','outerwear','accessories','homegoods','new-arrivals','sale'].map(h=>link(h)).join('')}</div><div><h3>MARCAS</h3>${['muttonhead','naked-and-famous','juniper-ridge','bather','beside'].map(h=>link(h)).join('')}</div><div><h3>NOSOTROS</h3><a href="/Karenza/pages/theme-features">Funciones de la tienda</a><a href="/Karenza/pages/about">Nosotros</a><a href="/Karenza/pages/faq">Preguntas frecuentes</a><a href="/Karenza/pages/contact-us">Contacto</a></div><a class="footer-brand" href="/Karenza/">KARENZA</a><div class="footer-newsletter"><h3>SUSCRÍBETE Y AHORRA UN 15 %</h3><p>Entérate antes que nadie de nuestras mejores ofertas. Nunca enviaremos más de un correo al mes.</p><form id="newsletter"><label class="sr-only" for="newsletter-email">Correo electrónico</label><input id="newsletter-email" type="email" placeholder="Introduce tu correo electrónico" required autocomplete="email"><button aria-label="Suscribirme" type="submit">✉</button></form><p class="form-note" id="newsletter-result" role="status"></p><div class="socials"><button data-action="social" aria-label="Instagram">◎</button><button data-action="social" aria-label="Facebook">f</button><button data-action="social" aria-label="Pinterest">Ⓟ</button></div></div></div><div class="footer-bottom"><button data-action="currency">Estados Unidos (USD $) <span class="chevron"></span></button><span>© ${new Date().getFullYear()} KARENZA</span><div class="payments" aria-label="Métodos de pago mostrados en la demostración"><span>VISA</span><span>●●</span><span>AMEX</span><span>PayPal</span><span> Pay</span></div></div>`;}
function collectionProducts(handle){return handle==='all'?[...products]:products.filter(p=>(collections[handle]||[]).includes(p.handle));}
function collectionPage(handle){let list=collectionProducts(handle);if(collectionFilter)list=list.filter(p=>p.vendor===collectionFilter);if(sortBy==='price-low')list.sort((a,b)=>a.price-b.price);if(sortBy==='price-high')list.sort((a,b)=>b.price-a.price);if(sortBy==='name')list.sort((a,b)=>a.title.localeCompare(b.title,'es'));const vendors=[...new Set(collectionProducts(handle).map(p=>p.vendor))];return `<section class="collection-heading"><p class="breadcrumb"><a href="/Karenza/">Inicio</a> / ${esc(titles[handle]||handle)}</p><h1>${esc((titles[handle]||handle).toUpperCase())}</h1><div class="collection-tabs">${['all','hats','t-shirts','jackets','sweatshirt','accessories'].map(h=>link(h)).join('')}</div></section><section class="collection-layout section"><aside class="filters"><h3>TIENDA</h3>${Object.keys(titles).slice(0,13).map(h=>link(h)).join('')}<details open><summary>Marca</summary><label><input type="radio" name="brand" value="" ${!collectionFilter?'checked':''}> Todas las marcas</label>${vendors.map(v=>`<label><input type="radio" name="brand" value="${esc(v)}" ${collectionFilter===v?'checked':''}> ${esc(v)}</label>`).join('')}</details></aside><div class="collection-results"><div class="collection-toolbar"><span>${list.length} productos</span><label>Ordenar por <select id="sort-products">${[['featured','Destacados'],['price-low','Precio: de menor a mayor'],['price-high','Precio: de mayor a menor'],['name','Nombre: de la A a la Z']].map(([v,t])=>`<option value="${v}" ${sortBy===v?'selected':''}>${t}</option>`).join('')}</select></label></div><div class="product-grid">${list.slice(0,pageLimit).map(card).join('')}</div>${list.length>pageLimit?'<button class="button load-more" data-action="load-more">CARGAR MÁS</button>':''}${!list.length?'<div class="empty-state"><h2>No encontramos productos</h2><p>Prueba con otra categoría o marca.</p><a class="button" href="/Karenza/collections/all">VER TODO</a></div>':''}</div></section>`;}
function productDetail(p,quick=false){return `<div class="product-detail ${quick?'quick-detail':''}" data-product="${p.handle}"><div class="product-gallery"><div class="main-product-image">${img(p.images[0],p.title)}<button data-action="zoom" aria-label="Ampliar imagen del producto">⌕</button></div><div class="thumbnails">${p.images.map((src,i)=>`<button data-image="${src}" aria-label="Ver imagen del producto ${i+1}" ${i===0?'class="selected"':''}>${img(src,p.title+' '+(i+1))}</button>`).join('')}</div></div><div class="product-info"><p class="vendor">${esc(p.vendor.toUpperCase())}</p><h1>${esc(p.title)}</h1><p class="product-price">${money(p.price)}</p><p class="tax-note">El envío se calcula al finalizar la compra.</p><hr><form class="add-form" data-handle="${p.handle}">${p.variants.length>1?`<label for="variant-${quick?'quick':'page'}">${esc(p.options.map(o=>o.name).join(' / '))}</label><select id="variant-${quick?'quick':'page'}" name="variant">${p.variants.map((v,i)=>`<option value="${i}">${esc(v.title)}</option>`).join('')}</select>`:'<p class="size-label">TALLA ÚNICA</p>'}<label>Cantidad</label><div class="quantity"><button type="button" data-quantity="-1" aria-label="Reducir cantidad">−</button><input aria-label="Cantidad" type="number" name="quantity" value="1" min="1" max="99"><button type="button" data-quantity="1" aria-label="Aumentar cantidad">+</button></div><button class="button add-button" type="submit">AÑADIR AL CARRITO</button></form><div class="product-description">${esc(p.description).replace(/\n/g,'<br>')}</div><details><summary>Envíos y devoluciones</summary><p>Devoluciones sin complicaciones durante 30 días. Esta tienda es una demostración; no se procesan pedidos ni pagos.</p></details>${quick?`<a class="text-link" href="/Karenza/products/${p.handle}">Ver todos los detalles →</a>`:''}</div></div>`;}
function productPage(handle){const p=getProduct(handle);if(!p)return notFound();return `<section class="section product-page"><p class="breadcrumb"><a href="/Karenza/">Inicio</a> / <a href="/Karenza/collections/all">Productos</a> / ${esc(p.title)}</p>${productDetail(p)}</section><section class="section"><h2>TAMBIÉN TE PUEDE GUSTAR</h2><div class="product-grid">${products.filter(x=>x.vendor===p.vendor&&x.handle!==p.handle).slice(0,4).map(card).join('')}</div></section>`;}
function searchPage(q=''){const found=products.filter(p=>fold(p.title+' '+p.vendor).includes(fold(q)));return `<section class="section search-page"><h1>BUSCAR</h1><form class="search-form"><label class="sr-only" for="page-search">Buscar productos</label><input id="page-search" name="q" value="${esc(q)}" placeholder="Busca en nuestra tienda" autofocus><button class="button" type="submit">BUSCAR</button></form><p>${q?`${found.length} resultados para «${esc(q)}»`:'Descubre nuestra colección'}</p><div class="product-grid">${found.slice(0,pageLimit).map(card).join('')}</div>${!found.length?'<div class="empty-state"><h2>No encontramos resultados</h2><p>Prueba con «gorro», «chaqueta» o el nombre de una marca.</p></div>':''}${found.length>pageLimit?'<button class="button load-more" data-action="load-more">CARGAR MÁS</button>':''}</section>`;}
function page(handle){if(handle==='faq')return `<section class="text-page section"><h1>PREGUNTAS FRECUENTES</h1>${[['¿Esta tienda ya está operativa?','Esta es la tienda de demostración de Karenza. Puedes explorar los productos y probar el carrito. Los pedidos, los pagos y las cuentas de cliente aún no están conectados.'],['¿Cuál es la política de devoluciones?','La tienda de referencia ofrece devoluciones en 30 días con el envío de retorno incluido. Las políticas definitivas de Karenza estarán disponibles cuando abra la tienda.'],['¿Dónde está la tienda?','La dirección de Toronto que se muestra forma parte de la demostración original.'],['¿Cómo elijo mi talla?','Abre un producto para consultar las tallas y variantes disponibles en el catálogo de demostración.']].map(([q,a])=>`<details><summary>${q}</summary><p>${a}</p></details>`).join('')}</section>`;if(handle==='contact-us')return `<section class="section contact-page"><div class="editorial-copy"><p class="eyebrow">VISÍTANOS</p><h1>CONOCE NUESTRA TIENDA</h1><p>337 Roncesvalles Ave, Toronto</p><p class="muted">Dirección de la tienda de demostración original.</p><a class="button" href="https://www.google.com/maps/search/?api=1&query=337+Roncesvalles+Ave+Toronto" target="_blank" rel="noopener">CÓMO LLEGAR</a></div>${img(section('promos_three').tiles[2].image,'Percheros con ropa en una boutique')}</section>`;if(handle==='theme-features')return `<section class="text-page section"><h1>FUNCIONES DE LA TIENDA</h1><p>Explora la tienda de Karenza.</p><div class="feature-links"><button data-action="search">Buscar en el catálogo →</button><button data-quick="chunky-toque-fawn-2">Vista rápida →</button><button data-action="cart">Carrito lateral →</button><a href="/Karenza/collections/all">Colecciones y filtros →</a></div></section>`;return `<section class="text-page section"><p class="eyebrow">KARENZA</p><h1>CALIDAD Y COMODIDAD</h1><p>Prendas esenciales de calidad. Detalles cuidados. Diseños atemporales para cada día.</p>${img(section('made_together').image,'Prendas esenciales de punto suave')}<a class="button" href="/Karenza/collections/all">EXPLORAR COLECCIÓN</a></section>`;}
function notFound(){return '<section class="section empty-state"><h1>PÁGINA NO ENCONTRADA</h1><a class="button" href="/Karenza/">VOLVER A KARENZA</a></section>';}
function render(){closeOverlay();closeMenu();const path=routePath();$('#header').classList.toggle('over-hero',path==='/');if(path==='/'){$('#main').innerHTML=home();document.title='Karenza — Calidad y comodidad';}else if(path.startsWith('/collections/')){$('#main').innerHTML=collectionPage(path.split('/')[2]);document.title=(titles[path.split('/')[2]]||'Colección')+' — Karenza';}else if(path.startsWith('/products/')){$('#main').innerHTML=productPage(path.split('/')[2]);document.title=(getProduct(path.split('/')[2])?.title||'Producto')+' — Karenza';}else if(path==='/search'){$('#main').innerHTML=searchPage(new URLSearchParams(location.search).get('q')||'');document.title='Buscar — Karenza';}else if(path.startsWith('/pages/')){$('#main').innerHTML=page(path.split('/')[2]);document.title='Karenza — '+({'about':'Nosotros','contact-us':'Contacto','faq':'Preguntas frecuentes','theme-features':'Funciones de la tienda'}[path.split('/')[2]]||'Tienda');}else if(path==='/cart'){$('#main').innerHTML='<section class="section"><div id="cart-page"></div></section>';$('#cart-page').innerHTML=cartHTML();}else $('#main').innerHTML=notFound();updateCartCount();sticky();}
function navigate(path){pageLimit=24;collectionFilter='';sortBy='featured';history.pushState({},'',siteUrl(path));render();window.scrollTo(0,0);}
function modal(html,kind=''){const d=$('#overlay');if(d.open)d.close();d.className=kind;$('#overlay-content').innerHTML=html;d.showModal();document.body.classList.add('modal-open');}
function closeOverlay(){if($('#overlay').open)$('#overlay').close();document.body.classList.remove('modal-open');}
function toast(text){$('#toast').textContent=text;$('#toast').classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),3500);}
function closeMenu(){$('#mega-menu').hidden=true;$$('[data-menu]').forEach(b=>b.setAttribute('aria-expanded','false'));}
function menu(type){const node=$('#mega-menu'),wasOpen=!node.hidden&&node.dataset.type===type;closeMenu();if(wasOpen)return;node.dataset.type=type;node.hidden=false;$(`[data-menu="${type}"]`)?.setAttribute('aria-expanded','true');node.innerHTML=type==='shop'?`<div><h3>ROPA</h3>${['apparel','t-shirts','sweatshirt','sweatpants','jackets','outerwear'].map(h=>link(h)).join('')}</div><div><h3>ACCESORIOS</h3>${['hats','accessories','homegoods'].map(h=>link(h)).join('')}<h3>DESCUBRE</h3>${link('new-arrivals')}${link('sale')}</div><a class="menu-image" href="/Karenza/collections/hats">${img(section('made_together').image,'Colección de prendas de punto')}<span>ESENCIALES PARA CADA DÍA</span></a>`:type==='brands'?`<div><h3>COMPRA POR MARCA</h3>${['muttonhead','naked-and-famous','juniper-ridge','bather','beside'].map(h=>link(h)).join('')}</div>`:`<div><h3>DESCUBRE KARENZA</h3><a href="/Karenza/pages/theme-features">Funciones de la tienda</a><a href="/Karenza/pages/about">Sobre nosotros</a><a href="/Karenza/pages/faq">Preguntas frecuentes</a><a href="/Karenza/pages/contact-us">Contacto</a></div>`;}
function cartLines(){return cart.map(c=>({c,p:getProduct(c.handle)})).filter(x=>x.p);}
function cartTotal(){return cartLines().reduce((sum,{c,p})=>sum+Number(p.variants[c.variant]?.price||p.price)*c.quantity,0);}
function saveCart(){try{localStorage.setItem('masion-cart',JSON.stringify(cart));}catch{}updateCartCount();}
function updateCartCount(){const count=cart.reduce((sum,c)=>sum+c.quantity,0);$('#cart-count').textContent=count;$('#cart-count').hidden=!count;}
function addToCart(handle,variant=0,quantity=1){const p=getProduct(handle);if(!p||!Number.isInteger(variant)||!p.variants[variant]||!Number.isInteger(quantity)||quantity<1||quantity>99)throw Error('Elige un producto, una variante y una cantidad válidos (de 1 a 99).');const existing=cart.find(c=>c.handle===handle&&c.variant===variant);if(existing)existing.quantity=Math.min(99,existing.quantity+quantity);else cart.push({handle,variant,quantity});saveCart();showCart();return {items:cart.reduce((sum,c)=>sum+c.quantity,0),subtotal:cartTotal(),currency:'USD',demo:true};}
function cartHTML(){return `<h2>TU CARRITO</h2>${cart.length?`<div class="cart-lines">${cartLines().map(({c,p})=>`<div class="cart-line">${img(p.images[0],p.title)}<div><a href="/Karenza/products/${p.handle}">${esc(p.title)}</a><small>${esc(p.variants[c.variant]?.title==='Predeterminado'?'':p.variants[c.variant]?.title||'')}</small><div class="quantity"><button data-cart-change="${cart.indexOf(c)}" data-delta="-1" aria-label="Reducir la cantidad de ${esc(p.title)}">−</button><span>${c.quantity}</span><button data-cart-change="${cart.indexOf(c)}" data-delta="1" aria-label="Aumentar la cantidad de ${esc(p.title)}">+</button></div><button class="remove" data-remove="${cart.indexOf(c)}">Eliminar</button></div><span>${money(Number(p.variants[c.variant]?.price||p.price)*c.quantity)}</span></div>`).join('')}</div><div class="cart-bottom"><p class="subtotal"><span>SUBTOTAL</span><strong>${money(cartTotal())}</strong></p><p>El envío, los impuestos y los descuentos se calculan al finalizar la compra.</p><label for="cart-note">Nota del pedido</label><textarea id="cart-note" placeholder="Añade una nota a tu pedido"></textarea><button class="button" data-action="checkout">FINALIZAR COMPRA</button><button class="text-link" data-action="close">Seguir comprando</button></div>`:'<div class="empty-state"><svg viewBox="0 0 24 24" width="50" fill="none" stroke="currentColor"><path d="M3 7h18v15H3ZM8 7V4a4 4 0 0 1 8 0v3"/></svg><p>Tu carrito está vacío.</p><a class="button" href="/Karenza/collections/all">SEGUIR COMPRANDO</a></div>'}`;}
function showCart(){modal(cartHTML(),'drawer cart-drawer');}
function sticky(){$('#header').classList.toggle('is-sticky',scrollY>170);document.body.classList.toggle('scrolled',scrollY>170&&routePath()!=='/');}
function setSlide(i){const s=section('hero').slides[i];$('#hero-image').src=i===0?'/Karenza/assets/hero.jpg':s.image;$('#hero-image').alt=s.heading;$('#hero-eyebrow').textContent=s.eyebrow;$('#hero-heading').textContent=s.heading;$('#hero-subtitle').textContent=['Prendas esenciales de calidad en seis nuevos colores','Diseñado con cuidado. Llévalo a tu manera.','Tus favoritos para el frío, reinventados.'][i];$('#hero-link').textContent=i===2?'VER PRENDAS SUPERIORES':s.cta;$('#hero-link').href=siteUrl(i===0?'/collections/hats':'/collections/all');$$('[data-slide]').forEach((b,j)=>b.setAttribute('aria-current',String(i===j)));}
document.addEventListener('click',event=>{const t=event.target.closest('a,button');if(!t)return;if(t.dataset.action){const action=t.dataset.action;
if(action==='close')closeOverlay();if(action==='cart')showCart();
if(action==='menu')modal(`<h2>KARENZA</h2><nav class="mobile-links">${['all','new-arrivals','muttonhead','hats','t-shirts','jackets','sweatshirt','homegoods'].map(h=>link(h,h==='all'?'Tienda':titles[h])).join('')}<details><summary>Comprar por marca</summary>${['muttonhead','naked-and-famous','juniper-ridge','bather','beside'].map(h=>link(h)).join('')}</details><a href="/Karenza/pages/about">Nosotros</a><a href="/Karenza/pages/contact-us">Contacto</a></nav>`,'drawer left-drawer');
if(action==='search')modal('<h2>BUSCAR</h2><form class="search-form"><label class="sr-only" for="search-query">Buscar productos</label><input id="search-query" name="q" placeholder="Busca en nuestra tienda" autofocus><button class="button">BUSCAR</button></form><div id="search-suggestions"></div>','search-modal');
if(action==='account')modal('<div class="empty-state"><h2>CUENTA DE CLIENTE</h2><p>Las cuentas de cliente estarán disponibles cuando abra Karenza.</p><p class="muted">Esta demostración no recoge datos de inicio de sesión.</p><button class="button" data-action="close">SEGUIR COMPRANDO</button></div>');
if(action==='checkout')modal(`<div class="empty-state"><p class="eyebrow">KARENZA</p><h2>PAGO DE DEMOSTRACIÓN</h2><p>Tu selección: ${money(cartTotal())}</p><p>El pago aún no está conectado. No se realizará ningún pedido ni se efectuará ningún cobro.</p><button class="button" data-action="cart">VOLVER AL CARRITO</button></div>`);
if(action==='currency')modal('<h2>PAÍS / REGIÓN</h2><label for="country-select">Selecciona tu región</label><select id="country-select"><option>Estados Unidos (USD $)</option><option>Canadá (USD $)</option><option>Perú (USD $)</option><option>Reino Unido (USD $)</option></select><p>Los precios de la demostración se muestran en dólares estadounidenses.</p><button class="button" data-action="region-save">ACTUALIZAR</button>');
if(action==='region-save'){const val=$('#country-select').value;$$('.currency,.footer-bottom>button').forEach(el=>el.textContent=val);closeOverlay();}
if(action==='social')modal('<h2>SIGUE A KARENZA</h2><p>Nuestras redes sociales estarán disponibles cuando abra la tienda.</p><button class="button" data-action="close">SEGUIR EXPLORANDO</button>');
if(action==='load-more'){const y=scrollY;pageLimit+=24;render();window.scrollTo(0,y);}
if(action==='zoom'){const current=t.closest('.main-product-image').querySelector('img');modal(`<img class="zoom-image" src="${current.src}" alt="${esc(current.alt)}">`,'zoom-modal');}return;}
if(t.dataset.quick){const p=getProduct(t.dataset.quick);if(p)modal(productDetail(p,true),'quick-modal');return;}
if(t.dataset.menu){menu(t.dataset.menu);return;}
if(t.dataset.look){$('#look-product').innerHTML=card(getProduct(t.dataset.look));return;}
if(t.dataset.image){const gallery=t.closest('.product-gallery');gallery.querySelector('.main-product-image img').src=t.dataset.image;gallery.querySelectorAll('.thumbnails button').forEach(b=>b.classList.toggle('selected',b===t));return;}
if(t.dataset.quantity){const input=t.closest('.quantity').querySelector('input');input.value=Math.max(1,Math.min(99,Number(input.value)+Number(t.dataset.quantity)));return;}
if(t.dataset.cartChange!==undefined){const i=Number(t.dataset.cartChange);cart[i].quantity=Math.min(99,cart[i].quantity+Number(t.dataset.delta));if(cart[i].quantity<1)cart.splice(i,1);saveCart();showCart();return;}
if(t.dataset.remove!==undefined){cart.splice(Number(t.dataset.remove),1);saveCart();showCart();return;}
if(t.dataset.slide!==undefined){setSlide(Number(t.dataset.slide));return;}
if(t.tagName==='A'&&!event.metaKey&&!event.ctrlKey&&!event.shiftKey){const url=new URL(t.href);if(url.origin===location.origin&&url.pathname.startsWith(SITE_BASE+'/')&&!url.hash){event.preventDefault();navigate(url.pathname+url.search);}}});
document.addEventListener('click',event=>{if(!event.target.closest('#header'))closeMenu();if(event.target===$('#overlay')){const box=$('#overlay').getBoundingClientRect();if(event.clientX<box.left||event.clientX>box.right||event.clientY<box.top||event.clientY>box.bottom)closeOverlay();}});
document.addEventListener('submit',event=>{if(event.target.matches('.add-form')){event.preventDefault();const data=new FormData(event.target);try{addToCart(event.target.dataset.handle,Number(data.get('variant')||0),Number(data.get('quantity')||1));}catch(error){toast(error.message);}}if(event.target.matches('.search-form')){event.preventDefault();navigate('/search?q='+encodeURIComponent(new FormData(event.target).get('q')||''));}if(event.target.id==='newsletter'){event.preventDefault();$('#newsletter-result').textContent='¡Gracias! Este formulario es de demostración; no se ha registrado ninguna suscripción ni enviado ningún correo.';event.target.reset();}});
document.addEventListener('input',event=>{if(event.target.id==='search-query'){const q=event.target.value.toLowerCase().trim();$('#search-suggestions').innerHTML=q?products.filter(p=>fold(p.title+' '+p.vendor).includes(fold(q))).slice(0,4).map(p=>`<a class="suggestion" href="/Karenza/products/${p.handle}">${img(p.images[0],p.title)}<span>${esc(p.title)}<small>${money(p.price)}</small></span></a>`).join('')||'<p>No encontramos productos. Prueba con «gorro» o «chaqueta».</p>':'';}});
document.addEventListener('change',event=>{if(event.target.id==='sort-products'){sortBy=event.target.value;const y=scrollY;render();window.scrollTo(0,y);}if(event.target.name==='brand'){collectionFilter=event.target.value;pageLimit=24;render();}});
document.addEventListener('keydown',event=>{if(event.key==='Escape')closeMenu();});$('#overlay').addEventListener('close',()=>document.body.classList.remove('modal-open'));window.addEventListener('popstate',render);window.addEventListener('scroll',sticky,{passive:true});
function registerTools(){const context=document.modelContext;if(!context?.registerTool)return;const specs=[{name:'search_catalog',description:'Busca productos en el catálogo de demostración de Karenza sin modificar el carrito.',inputSchema:{type:'object',properties:{query:{type:'string'}},required:['query'],additionalProperties:false},annotations:{readOnlyHint:true},execute:({query})=>{if(typeof query!=='string')throw Error('La búsqueda debe ser un texto');return products.filter(p=>fold(p.title+' '+p.vendor).includes(fold(query))).slice(0,10).map(p=>({handle:p.handle,title:p.title,price:Number(p.price),currency:'USD'}));}},{name:'read_demo_cart',description:'Consulta el carrito de demostración actual de Karenza.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({items:cartLines().map(({c,p})=>({...c,title:p.title})),subtotal:cartTotal(),currency:'USD',demo:true})},{name:'add_to_demo_cart',description:'Añade un producto al carrito local de demostración y abre el panel del carrito. No realiza pedidos ni procesa pagos.',inputSchema:{type:'object',properties:{handle:{type:'string'},quantity:{type:'integer',minimum:1,maximum:99},variant:{type:'integer',minimum:0}},required:['handle','quantity'],additionalProperties:false},annotations:{readOnlyHint:false},execute:({handle,quantity,variant=0})=>addToCart(handle,variant,quantity)}];for(const tool of specs){try{Promise.resolve(context.registerTool(tool)).catch(()=>{});}catch{}}}
Promise.all(['/catalog.json','/sections.json','/collections.json'].map(url=>fetch(siteUrl(url)).then(r=>{if(!r.ok)throw Error('No se pudo cargar la colección');return r.json();}))).then(([p,s,c])=>{products=p;sections=s;collections=c;cart=cart.filter(x=>getProduct(x.handle)&&Number.isInteger(x.quantity)&&x.quantity>0&&x.quantity<=99&&getProduct(x.handle).variants[x.variant]);$('#footer').innerHTML=footer();render();registerTools();}).catch(()=>{$('#main').innerHTML='<section class="empty-state section"><h1>VOLVEMOS ENSEGUIDA</h1><p>No pudimos cargar la colección.</p><a class="button" href="/Karenza/">VOLVER A INTENTAR</a></section>';});
